// Add New Student with POST request
POST http://localhost:3000/student HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "class": 3,
    "studentNumber": 19
}

###
// get all students
GET http://localhost:3000/student HTTP/1.1

###
// get student with number in url
GET http://localhost:3000/student/222 HTTP/1.1

###
// delete student with number in url
DELETE http://localhost:3000/student/212 HTTP/1.1

###
// add new class
POST http://localhost:3000/class HTTP/1.1
content-type: application/json

{
    "classNumber": 3
}
###
// get all classes
GET http://localhost:3000/class HTTP/1.1

###
// get class with number in url
GET http://localhost:3000/class/2 HTTP/1.1


###
// delete class and all students in the class
DELETE http://localhost:3000/class/3 HTTP/1.1

###
// add new homework
POST http://localhost:3000/homework HTTP/1.1
content-type: application/json

{
    "studentNumber": 22,
    "description": "Solve 22 math test"
}

###
//Delete Homework
DELETE http://localhost:3000/homework/1 HTTP/1.1

###
// get all homeworks
GET http://localhost:3000/homework HTTP/1.1

###
// get class with number in url
GET http://localhost:3000/homework/4 HTTP/1.1