// Add New Student with POST request
POST http://localhost:3000/student HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "class": 15,
    "studentNumber": 853
}

###
// get all students
GET http://localhost:3000/student HTTP/1.1

###
// get student with number in url
GET http://localhost:3000/student/2 HTTP/1.1

###
// delete student with number in url
DELETE http://localhost:3000/student/880 HTTP/1.1

###
// add new class
POST http://localhost:3000/class HTTP/1.1
content-type: application/json

{
    "classNumber": 15,
    "studentCount": 0
}

###
// delete class and all students in the class
DELETE http://localhost:3000/class/10 HTTP/1.1