// Add New Student with POST request
POST http://localhost:3000/student HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "class": 2,
    "studentNumber": 4
}

###
// get all students
GET http://localhost:3000/student HTTP/1.1

###
// get student with number in url
GET http://localhost:3000/student/1 HTTP/1.1

###
// delete student with number in url
DELETE http://localhost:3000/student/3 HTTP/1.1

###
// add new class
POST http://localhost:3000/class HTTP/1.1
content-type: application/json

{
    "classNumber": 2
}

###
// delete class and all students in the class
DELETE http://localhost:3000/class/2 HTTP/1.1

###
// add new homework
POST http://localhost:3000/homework HTTP/1.1
content-type: application/json

{
    "studentNumber": 4,
    "description": "Solve 2 math test"
}

###
DELETE http://localhost:3000/homework/4 HTTP/1.1